version: '3.9'

services:  
    web:
        build:
            context: ./src
            dockerfile: Dockerfile
        restart: on-failure
        ports:
          - 8080:80
        depends_on:
          - db
        networks:
          - aspnetcoreapp-network
    db:
        image: postgres:14.10
        restart: on-failure
        environment:
          - POSTGRES_DB=notification_service
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Suhrob1999
        ports:
          - 54432:5432
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        networks:
          - aspnetcoreapp-network
            
networks:
    aspnetcoreapp-network:
        driver: bridge
                